import type { BaseEvent, CreatedEvent, EventFlowMap } from '@schemeless/event-store-types';
import { getEventFlow } from '../operators/getEventFlow';
import { logEvent } from '../util/logEvent';
import { logger } from '../util/logger';

export interface SideEffectRunnerOptions {
  maxRetries?: number;
}

export interface SideEffectResult {
  event: CreatedEvent<any>;
  newEvents: BaseEvent<any>[];
  status: 'done' | 'no_side_effect';
}

/**
 * Runs side effects for a list of processed events.
 * Returns any new events generated by side effects.
 *
 * Retry logic is per-event, controlled by flow.meta.sideEffectFailedRetryAllowed.
 */
export async function runSideEffects(
  events: CreatedEvent<any>[],
  eventFlowMap: EventFlowMap
): Promise<SideEffectResult[]> {
  const results: SideEffectResult[] = [];

  for (const event of events) {
    const flow = getEventFlow(eventFlowMap)(event);

    if (!flow.sideEffect) {
      logEvent(event, '🌠', 'SideEffect:N/A');
      results.push({ event, newEvents: [], status: 'no_side_effect' });
      continue;
    }

    const maxRetries = flow.meta?.sideEffectFailedRetryAllowed ?? 0;
    let lastError: unknown;

    for (let attempt = 0; attempt <= maxRetries; attempt++) {
      try {
        const nextEvents = await flow.sideEffect(event);
        logEvent(event, '🌠', 'SideEffect:Done');
        results.push({
          event,
          newEvents: Array.isArray(nextEvents) ? nextEvents : [],
          status: 'done',
        });
        lastError = undefined;
        break;
      } catch (error) {
        lastError = error;
        logger.error(`Side effect failed (attempt ${attempt + 1}/${maxRetries + 1}): ${error}`);
        if (attempt < maxRetries) {
          logEvent(event, '🌠', `SE:Retry:${attempt}`);
        }
      }
    }

    if (lastError) {
      logEvent(event, '🌠', `SE:FAILED`);
      // Side effect failure is non-fatal — event is already persisted
      results.push({ event, newEvents: [], status: 'done' });
    }
  }

  return results;
}
